version: '3.8'
services:
  core:
    container_name: connect-emp-core
    image: ghcr.io/mrexmelle/connect-emp:0.1.0
    environment:
      - APP_PROFILE=docked
    ports:
      - '8082:8082'
    networks:
      - connect_proxy_network

networks:
  connect_proxy_network:
      name: connect-network
      external: true
