app:
  datasource:
    read:
      host: 127.0.0.1
      port: 5432
      user: emp_r
      password: 123
      dbname: emp
      sslmode: disable
      timezone: Asia/Jakarta
    write:
      host: 127.0.0.1
      port: 5432
      user: emp_w
      password: 123
      dbname: emp
      sslmode: disable
      timezone: Asia/Jakarta
  server:
    port: 8082
  client:
    authx:
      host: http://127.0.0.1
      port: 8080